name: 06-contexts

on: [
  push,
  workflow_dispatch
]

env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"

      - name: Retrieve Variable
        run: |
          echo "Value of MY_VAR is: ${{ vars.MY_VAR }}"

      - name: Print With Single Inner Env Variables
        env: 
          MY_OVERWRITTEN_VAR: "step overwrite env"
          MY_JOB_VAR: "step job env"
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
          echo "Job env: ${{ env.MY_JOB_VAR }}"

      - name: Print Without Inner Env Variables
        env: 
          MY_WORKFLOW_VAR: "step workflow env"
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
          echo "Job env: ${{ env.MY_JOB_VAR }}"